import 'package:sreerajp_todo/core/utils/date_utils.dart';
import 'package:sreerajp_todo/domain/repositories/recurrence_rule_repository.dart';
import 'package:sreerajp_todo/domain/repositories/todo_repository.dart';

class DeleteRecurringTodos {
  DeleteRecurringTodos(this._todoRepository, this._recurrenceRuleRepository);

  final TodoRepository _todoRepository;
  final RecurrenceRuleRepository _recurrenceRuleRepository;

  /// Deletes every occurrence (past and future) generated by
  /// [recurrenceRuleId] and the rule itself. Removing the rule is essential:
  /// otherwise GenerateRecurringTasks would regenerate the occurrences on the
  /// next app launch.
  /// Returns the number of todos deleted.
  Future<int> all(String recurrenceRuleId) async {
    final count = await _todoRepository.deleteAllByRecurrenceRuleId(
      recurrenceRuleId,
    );
    await _recurrenceRuleRepository.delete(recurrenceRuleId);
    return count;
  }

  /// Deletes today's and all future occurrences of [recurrenceRuleId], then
  /// ends the rule at yesterday so it stops generating new occurrences while
  /// past occurrences (history) are preserved.
  /// Returns the number of todos deleted.
  Future<int> thisAndFuture(String recurrenceRuleId) async {
    final count = await _todoRepository.deleteByRecurrenceRuleIdFromDate(
      recurrenceRuleId,
      todayAsIso(),
    );

    final rule = await _recurrenceRuleRepository.findById(recurrenceRuleId);
    if (rule != null) {
      final now = DateTime.now();
      // DateTime normalises day - 1 across month/year boundaries, and the
      // wall-clock construction avoids DST duration pitfalls.
      final yesterday = dateTimeToIso(
        DateTime(now.year, now.month, now.day - 1),
      );
      await _recurrenceRuleRepository.update(rule.copyWith(endDate: yesterday));
    }

    return count;
  }
}
