// GENERATED by tool/ritual_deck_to_arb.dart. Do not edit by hand.
//
// Maps a Ritual Deck card id to its text in the app's current language.
//
// The ARB getters are generated methods, so a card's text cannot be looked up
// by key at run time. This switch is the bridge. It is generated from the same
// source as the ARB entries, so the two can never disagree.

import 'package:sreerajp_todo/l10n/app_localizations.dart';

/// The four pieces of text on one Ritual Deck card.
class RitualCardText {
  const RitualCardText({
    required this.title,
    required this.prompt,
    required this.quote,
    required this.author,
  });

  /// Short name of the card, shown as its heading.
  final String title;

  /// The reflection question the card asks.
  final String prompt;

  /// The grounding quote below the question.
  final String quote;

  /// Who the quote is from.
  final String author;
}

/// Returns the text for [cardId] in the language [l10n] is set to.
///
/// An unknown id falls back to the first card rather than throwing: a stale id
/// can only come from a downgrade or a hand-edited preferences file, and must
/// never stop the ritual from opening.
RitualCardText ritualCardText(AppLocalizations l10n, String cardId) {
  switch (cardId) {
    case 'sd_01':
      return RitualCardText(
        title: l10n.ritualCardSd01Title,
        prompt: l10n.ritualCardSd01Prompt,
        quote: l10n.ritualCardSd01Quote,
        author: l10n.ritualCardSd01QuoteAuthor,
      );
    case 'sd_02':
      return RitualCardText(
        title: l10n.ritualCardSd02Title,
        prompt: l10n.ritualCardSd02Prompt,
        quote: l10n.ritualCardSd02Quote,
        author: l10n.ritualCardSd02QuoteAuthor,
      );
    case 'sd_03':
      return RitualCardText(
        title: l10n.ritualCardSd03Title,
        prompt: l10n.ritualCardSd03Prompt,
        quote: l10n.ritualCardSd03Quote,
        author: l10n.ritualCardSd03QuoteAuthor,
      );
    case 'sd_04':
      return RitualCardText(
        title: l10n.ritualCardSd04Title,
        prompt: l10n.ritualCardSd04Prompt,
        quote: l10n.ritualCardSd04Quote,
        author: l10n.ritualCardSd04QuoteAuthor,
      );
    case 'sd_05':
      return RitualCardText(
        title: l10n.ritualCardSd05Title,
        prompt: l10n.ritualCardSd05Prompt,
        quote: l10n.ritualCardSd05Quote,
        author: l10n.ritualCardSd05QuoteAuthor,
      );
    case 'sd_06':
      return RitualCardText(
        title: l10n.ritualCardSd06Title,
        prompt: l10n.ritualCardSd06Prompt,
        quote: l10n.ritualCardSd06Quote,
        author: l10n.ritualCardSd06QuoteAuthor,
      );
    case 'sd_07':
      return RitualCardText(
        title: l10n.ritualCardSd07Title,
        prompt: l10n.ritualCardSd07Prompt,
        quote: l10n.ritualCardSd07Quote,
        author: l10n.ritualCardSd07QuoteAuthor,
      );
    case 'sd_08':
      return RitualCardText(
        title: l10n.ritualCardSd08Title,
        prompt: l10n.ritualCardSd08Prompt,
        quote: l10n.ritualCardSd08Quote,
        author: l10n.ritualCardSd08QuoteAuthor,
      );
    case 'sd_09':
      return RitualCardText(
        title: l10n.ritualCardSd09Title,
        prompt: l10n.ritualCardSd09Prompt,
        quote: l10n.ritualCardSd09Quote,
        author: l10n.ritualCardSd09QuoteAuthor,
      );
    case 'sd_10':
      return RitualCardText(
        title: l10n.ritualCardSd10Title,
        prompt: l10n.ritualCardSd10Prompt,
        quote: l10n.ritualCardSd10Quote,
        author: l10n.ritualCardSd10QuoteAuthor,
      );
    case 'sd_11':
      return RitualCardText(
        title: l10n.ritualCardSd11Title,
        prompt: l10n.ritualCardSd11Prompt,
        quote: l10n.ritualCardSd11Quote,
        author: l10n.ritualCardSd11QuoteAuthor,
      );
    case 'sd_12':
      return RitualCardText(
        title: l10n.ritualCardSd12Title,
        prompt: l10n.ritualCardSd12Prompt,
        quote: l10n.ritualCardSd12Quote,
        author: l10n.ritualCardSd12QuoteAuthor,
      );
    case 'sd_13':
      return RitualCardText(
        title: l10n.ritualCardSd13Title,
        prompt: l10n.ritualCardSd13Prompt,
        quote: l10n.ritualCardSd13Quote,
        author: l10n.ritualCardSd13QuoteAuthor,
      );
    case 'sd_14':
      return RitualCardText(
        title: l10n.ritualCardSd14Title,
        prompt: l10n.ritualCardSd14Prompt,
        quote: l10n.ritualCardSd14Quote,
        author: l10n.ritualCardSd14QuoteAuthor,
      );
    case 'sd_15':
      return RitualCardText(
        title: l10n.ritualCardSd15Title,
        prompt: l10n.ritualCardSd15Prompt,
        quote: l10n.ritualCardSd15Quote,
        author: l10n.ritualCardSd15QuoteAuthor,
      );
    case 'sd_16':
      return RitualCardText(
        title: l10n.ritualCardSd16Title,
        prompt: l10n.ritualCardSd16Prompt,
        quote: l10n.ritualCardSd16Quote,
        author: l10n.ritualCardSd16QuoteAuthor,
      );
    case 'sd_17':
      return RitualCardText(
        title: l10n.ritualCardSd17Title,
        prompt: l10n.ritualCardSd17Prompt,
        quote: l10n.ritualCardSd17Quote,
        author: l10n.ritualCardSd17QuoteAuthor,
      );
    case 'sd_18':
      return RitualCardText(
        title: l10n.ritualCardSd18Title,
        prompt: l10n.ritualCardSd18Prompt,
        quote: l10n.ritualCardSd18Quote,
        author: l10n.ritualCardSd18QuoteAuthor,
      );
    case 'sd_19':
      return RitualCardText(
        title: l10n.ritualCardSd19Title,
        prompt: l10n.ritualCardSd19Prompt,
        quote: l10n.ritualCardSd19Quote,
        author: l10n.ritualCardSd19QuoteAuthor,
      );
    case 'sd_20':
      return RitualCardText(
        title: l10n.ritualCardSd20Title,
        prompt: l10n.ritualCardSd20Prompt,
        quote: l10n.ritualCardSd20Quote,
        author: l10n.ritualCardSd20QuoteAuthor,
      );
    case 'sd_21':
      return RitualCardText(
        title: l10n.ritualCardSd21Title,
        prompt: l10n.ritualCardSd21Prompt,
        quote: l10n.ritualCardSd21Quote,
        author: l10n.ritualCardSd21QuoteAuthor,
      );
    case 'sd_22':
      return RitualCardText(
        title: l10n.ritualCardSd22Title,
        prompt: l10n.ritualCardSd22Prompt,
        quote: l10n.ritualCardSd22Quote,
        author: l10n.ritualCardSd22QuoteAuthor,
      );
    case 'sd_23':
      return RitualCardText(
        title: l10n.ritualCardSd23Title,
        prompt: l10n.ritualCardSd23Prompt,
        quote: l10n.ritualCardSd23Quote,
        author: l10n.ritualCardSd23QuoteAuthor,
      );
    case 'sd_24':
      return RitualCardText(
        title: l10n.ritualCardSd24Title,
        prompt: l10n.ritualCardSd24Prompt,
        quote: l10n.ritualCardSd24Quote,
        author: l10n.ritualCardSd24QuoteAuthor,
      );
    case 'sd_25':
      return RitualCardText(
        title: l10n.ritualCardSd25Title,
        prompt: l10n.ritualCardSd25Prompt,
        quote: l10n.ritualCardSd25Quote,
        author: l10n.ritualCardSd25QuoteAuthor,
      );
    case 'sd_26':
      return RitualCardText(
        title: l10n.ritualCardSd26Title,
        prompt: l10n.ritualCardSd26Prompt,
        quote: l10n.ritualCardSd26Quote,
        author: l10n.ritualCardSd26QuoteAuthor,
      );
    case 'sd_27':
      return RitualCardText(
        title: l10n.ritualCardSd27Title,
        prompt: l10n.ritualCardSd27Prompt,
        quote: l10n.ritualCardSd27Quote,
        author: l10n.ritualCardSd27QuoteAuthor,
      );
    case 'sd_28':
      return RitualCardText(
        title: l10n.ritualCardSd28Title,
        prompt: l10n.ritualCardSd28Prompt,
        quote: l10n.ritualCardSd28Quote,
        author: l10n.ritualCardSd28QuoteAuthor,
      );
    case 'sd_29':
      return RitualCardText(
        title: l10n.ritualCardSd29Title,
        prompt: l10n.ritualCardSd29Prompt,
        quote: l10n.ritualCardSd29Quote,
        author: l10n.ritualCardSd29QuoteAuthor,
      );
    case 'sd_30':
      return RitualCardText(
        title: l10n.ritualCardSd30Title,
        prompt: l10n.ritualCardSd30Prompt,
        quote: l10n.ritualCardSd30Quote,
        author: l10n.ritualCardSd30QuoteAuthor,
      );
    case 'sd_31':
      return RitualCardText(
        title: l10n.ritualCardSd31Title,
        prompt: l10n.ritualCardSd31Prompt,
        quote: l10n.ritualCardSd31Quote,
        author: l10n.ritualCardSd31QuoteAuthor,
      );
    case 'sd_32':
      return RitualCardText(
        title: l10n.ritualCardSd32Title,
        prompt: l10n.ritualCardSd32Prompt,
        quote: l10n.ritualCardSd32Quote,
        author: l10n.ritualCardSd32QuoteAuthor,
      );
    case 'sd_33':
      return RitualCardText(
        title: l10n.ritualCardSd33Title,
        prompt: l10n.ritualCardSd33Prompt,
        quote: l10n.ritualCardSd33Quote,
        author: l10n.ritualCardSd33QuoteAuthor,
      );
    case 'sd_34':
      return RitualCardText(
        title: l10n.ritualCardSd34Title,
        prompt: l10n.ritualCardSd34Prompt,
        quote: l10n.ritualCardSd34Quote,
        author: l10n.ritualCardSd34QuoteAuthor,
      );
    case 'sd_35':
      return RitualCardText(
        title: l10n.ritualCardSd35Title,
        prompt: l10n.ritualCardSd35Prompt,
        quote: l10n.ritualCardSd35Quote,
        author: l10n.ritualCardSd35QuoteAuthor,
      );
    case 'sd_36':
      return RitualCardText(
        title: l10n.ritualCardSd36Title,
        prompt: l10n.ritualCardSd36Prompt,
        quote: l10n.ritualCardSd36Quote,
        author: l10n.ritualCardSd36QuoteAuthor,
      );
    case 'sd_37':
      return RitualCardText(
        title: l10n.ritualCardSd37Title,
        prompt: l10n.ritualCardSd37Prompt,
        quote: l10n.ritualCardSd37Quote,
        author: l10n.ritualCardSd37QuoteAuthor,
      );
    case 'sd_38':
      return RitualCardText(
        title: l10n.ritualCardSd38Title,
        prompt: l10n.ritualCardSd38Prompt,
        quote: l10n.ritualCardSd38Quote,
        author: l10n.ritualCardSd38QuoteAuthor,
      );
    case 'sd_39':
      return RitualCardText(
        title: l10n.ritualCardSd39Title,
        prompt: l10n.ritualCardSd39Prompt,
        quote: l10n.ritualCardSd39Quote,
        author: l10n.ritualCardSd39QuoteAuthor,
      );
    case 'sd_40':
      return RitualCardText(
        title: l10n.ritualCardSd40Title,
        prompt: l10n.ritualCardSd40Prompt,
        quote: l10n.ritualCardSd40Quote,
        author: l10n.ritualCardSd40QuoteAuthor,
      );
    case 'sd_41':
      return RitualCardText(
        title: l10n.ritualCardSd41Title,
        prompt: l10n.ritualCardSd41Prompt,
        quote: l10n.ritualCardSd41Quote,
        author: l10n.ritualCardSd41QuoteAuthor,
      );
    case 'sd_42':
      return RitualCardText(
        title: l10n.ritualCardSd42Title,
        prompt: l10n.ritualCardSd42Prompt,
        quote: l10n.ritualCardSd42Quote,
        author: l10n.ritualCardSd42QuoteAuthor,
      );
    case 'sd_43':
      return RitualCardText(
        title: l10n.ritualCardSd43Title,
        prompt: l10n.ritualCardSd43Prompt,
        quote: l10n.ritualCardSd43Quote,
        author: l10n.ritualCardSd43QuoteAuthor,
      );
    case 'sd_44':
      return RitualCardText(
        title: l10n.ritualCardSd44Title,
        prompt: l10n.ritualCardSd44Prompt,
        quote: l10n.ritualCardSd44Quote,
        author: l10n.ritualCardSd44QuoteAuthor,
      );
    case 'sd_45':
      return RitualCardText(
        title: l10n.ritualCardSd45Title,
        prompt: l10n.ritualCardSd45Prompt,
        quote: l10n.ritualCardSd45Quote,
        author: l10n.ritualCardSd45QuoteAuthor,
      );
    case 'sd_46':
      return RitualCardText(
        title: l10n.ritualCardSd46Title,
        prompt: l10n.ritualCardSd46Prompt,
        quote: l10n.ritualCardSd46Quote,
        author: l10n.ritualCardSd46QuoteAuthor,
      );
    case 'sd_47':
      return RitualCardText(
        title: l10n.ritualCardSd47Title,
        prompt: l10n.ritualCardSd47Prompt,
        quote: l10n.ritualCardSd47Quote,
        author: l10n.ritualCardSd47QuoteAuthor,
      );
    case 'sd_48':
      return RitualCardText(
        title: l10n.ritualCardSd48Title,
        prompt: l10n.ritualCardSd48Prompt,
        quote: l10n.ritualCardSd48Quote,
        author: l10n.ritualCardSd48QuoteAuthor,
      );
    case 'sd_49':
      return RitualCardText(
        title: l10n.ritualCardSd49Title,
        prompt: l10n.ritualCardSd49Prompt,
        quote: l10n.ritualCardSd49Quote,
        author: l10n.ritualCardSd49QuoteAuthor,
      );
    case 'sd_50':
      return RitualCardText(
        title: l10n.ritualCardSd50Title,
        prompt: l10n.ritualCardSd50Prompt,
        quote: l10n.ritualCardSd50Quote,
        author: l10n.ritualCardSd50QuoteAuthor,
      );
    default:
      return RitualCardText(
        title: l10n.ritualCardSd01Title,
        prompt: l10n.ritualCardSd01Prompt,
        quote: l10n.ritualCardSd01Quote,
        author: l10n.ritualCardSd01QuoteAuthor,
      );
  }
}
